# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: Phase_1
  displayName: Build and Test
  timeoutInMinutes: 180
          
  pool:
    name: Pipelines-SelfHostedAgent
  strategy:
    matrix:
      Python37:
        python.version: '3.7'

#Replace Variables value
  steps:
  - task: replacetokens@3
    inputs:
      rootDirectory: 'IntegrationTest'
      targetFiles: 'variablesfile.yaml'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      enableTransforms: false
      enableTelemetry: true
    displayName: 'Replace Variables value'

#Use Python 3.7
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

#Install Robot framework 
  - script: |
      pip install robotframework robotframework-seleniumlibrary webdrivermanager 
    displayName: 'Install Robot framework'

#Install Python Yaml
  - script: |
      pip install pyyaml
    displayName: 'Install Python Yaml'

#Run Robot Scripts - AddEditDeleteUser
  - script: |
      robot --pythonpath . -x AddEditDeleteUser.xml AddEditDeleteUser.robot
    workingDirectory: IntegrationTest
    displayName: 'Run Robot Scripts - AddEditDeleteUser'
    continueOnError: true

#Publish Test Results - AddEditDeleteUser  
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/AddEditDeleteUser.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
    displayName: 'Publish Test Results - AddEditDeleteUser'
    continueOnError: true
    condition: succeededOrFailed()


#Run Robot Scripts - Alerts
  - script: |
      pytest
      robot --pythonpath . -x Alerts.xml Alerts.robot
    workingDirectory: IntegrationTest
    displayName: 'Run Robot Scripts - Alerts'
    continueOnError: true
    enabled: false

#Publish Test Results - Alerts  
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/Alerts.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
    displayName: 'Publish Test Results - Alerts'
    continueOnError: true
    condition: succeededOrFailed()
    enabled: false

#Run Robot Scripts - Counter
  - script: |
      pytest
      robot --pythonpath . -x Counter.xml Counter.robot
    workingDirectory: IntegrationTest
    displayName: 'Run Robot Scripts - Counter'
    continueOnError: true
    enabled: false

#Publish Test Results - Counter  
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/Counter.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
    displayName: 'Publish Test Results - Counter'
    continueOnError: true
    condition: succeededOrFailed()
    enabled: false

#DeleteFiles
  - task: DeleteFiles@1
    displayName: 'Delete files from agent build directory'
    inputs:
      SourceFolder: '$(Agent.BuildDirectory)'
      Contents: |
       a*
       b*
       **/s/IntegrationTest*
      RemoveSourceFolder: true
